<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config\smartagriguard-ec6f7-firebase-adminsdk-fbsvc-b1a7544328.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\smartagriguard-ec6f7-firebase-adminsdk-fbsvc-b1a7544328.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.22" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.22" />
    <PackageReference Include="QuestPDF" Version="2025.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationLayer\ApplicationLayer.csproj" />
  </ItemGroup>

</Project>
