using DataAccessLayer.Data;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Repositories
{
    /// <summary>
    /// Repository managing the storage and retrieval of plant predictions.
    /// Predictions typically represent AI-driven insights, harvest forecasts, or health assessments.
    /// </summary>
    public class PredictionRepository : IPredictionRepository
    {
        private readonly SmartAgriGuardDbContext _context;

        public PredictionRepository(SmartAgriGuardDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Persists a new prediction record to the database.
        /// </summary>
        /// <param name="prediction">The prediction entity generated by the system.</param>
        public async Task AddAsync(Prediction prediction)
        {
            try
            {
                await _context.Predictions.AddAsync(prediction);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex) {
                throw new Exception("An error occurred while adding the prediction.", ex);
            }
        }

        /// <summary>
        /// Retrieves a specific prediction by its unique identifier, including the related Plant details.
        /// </summary>
        /// <param name="id">The GUID of the prediction.</param>
        /// <returns>A Prediction entity if found; otherwise, null.</returns>
        public async Task<Prediction?> GetByIdAsync(Guid id)
        {
            try
            {
                return await _context.Predictions
                    .Include(p => p.Plant)
                    .FirstOrDefaultAsync(p => p.Id == id);
            }
            catch (Exception ex) {
                throw new Exception("An error occurred while retrieving the prediction by ID.", ex);
            }
        }

        /// <summary>
        /// Retrieves all predictions stored in the system, mapped to their respective plants.
        /// </summary>
        /// <returns>A list of all predictions with plant metadata.</returns>
        public async Task<List<Prediction>> GetAllAsync()
        {
            try
            {
                return await _context.Predictions
                    .Include(p => p.Plant)
                    .ToListAsync();
            }
            catch (Exception ex)
            {
                throw new Exception("An error occurred while retrieving all predictions.", ex);
            }
        }

        /// <summary>
        /// Updates an existing prediction record (e.g., updating a status or confidence score).
        /// </summary>
        /// <param name="prediction">The updated prediction entity.</param>
        public async Task UpdateAsync(Prediction prediction)
        {
            try
            {
                _context.Predictions.Update(prediction);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                throw new Exception("An error occurred while updating the prediction.", ex);
            }
        }

        /// <summary>
        /// Permanently removes a prediction from the system.
        /// </summary>
        /// <param name="id">The GUID of the prediction to delete.</param>
        public async Task DeleteAsync(Guid id)
        {
            try
            {
                var prediction = await _context.Predictions.FindAsync(id);
                if (prediction != null)
                {
                    _context.Predictions.Remove(prediction);
                    await _context.SaveChangesAsync();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("An error occurred while deleting the prediction.", ex);
            }
        }
    }
}