// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYs26VDlxMpq1bS69oTXhWBHHeQQ7pZzo',
    appId: '1:280716392257:web:47800d7ccd6562c61093c0',
    messagingSenderId: '280716392257',
    projectId: 'smartagriguard-ec6f7',
    authDomain: 'smartagriguard-ec6f7.firebaseapp.com',
    storageBucket: 'smartagriguard-ec6f7.firebasestorage.app',
    measurementId: 'G-3VF9BLM45E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDoc8nTLKMr8RJoS6b24Vub7OMFoNCq0',
    appId: '1:280716392257:android:b5b41d6df73d37551093c0',
    messagingSenderId: '280716392257',
    projectId: 'smartagriguard-ec6f7',
    storageBucket: 'smartagriguard-ec6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpElm0lsNDT03O9_b7pJ_BUZK5qhcTvLE',
    appId: '1:280716392257:ios:fd82816829de4a661093c0',
    messagingSenderId: '280716392257',
    projectId: 'smartagriguard-ec6f7',
    storageBucket: 'smartagriguard-ec6f7.firebasestorage.app',
    iosBundleId: 'com.smartagriguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpElm0lsNDT03O9_b7pJ_BUZK5qhcTvLE',
    appId: '1:280716392257:ios:fd82816829de4a661093c0',
    messagingSenderId: '280716392257',
    projectId: 'smartagriguard-ec6f7',
    storageBucket: 'smartagriguard-ec6f7.firebasestorage.app',
    iosBundleId: 'com.smartagriguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYs26VDlxMpq1bS69oTXhWBHHeQQ7pZzo',
    appId: '1:280716392257:web:7b5467e6b2bee4fa1093c0',
    messagingSenderId: '280716392257',
    projectId: 'smartagriguard-ec6f7',
    authDomain: 'smartagriguard-ec6f7.firebaseapp.com',
    storageBucket: 'smartagriguard-ec6f7.firebasestorage.app',
    measurementId: 'G-K50MPSEH0L',
  );

}